### ISSUE TITLE
[frontend][feature] Components To Watch Videos

### ISSUE THREAD

**Issue by kzkaneoka** [kzkaneoka/reddit-videos#1]
### Description

Like a dating app, users can watch videos one by one and select either `like,` `okay`, `dislike`, or `skip.`

In this issue, we need components to watch videos.

### Workflow

1. A user watches videos one by one.
2. A user can select either `like`, `okay`, `dislike`, or `skip` at any time.
3. The next video shows up after selecting.
4. A user can go back to the prev video as well. There is no go back option if a user is watching the first video.
5. The order of videos is random.

### Note

- Please check **the Frontend section** in [README.md](https://github.com/kzkaneoka/reddit-short-videos) about how to setup API Calls.

**Comment by sujeongy** [comment]
@kzkaneoka
Can I use another UI framwork? like.. [`antd`](https://ant.design/)?
I've tried to understand 'tinder' UI. So I downloaded it.😂

**Comment by kzkaneoka** [comment]
Of course! Anything is up to you :)

**Comment by sujeongy** [comment]
> Of course! Anything is up to you :)

Thanks, matey😉
