### ISSUE TITLE
[backend][feature] CRUD Functionalities For Videos

### ISSUE THREAD

**Issue by kzkaneoka** [kzkaneoka/reddit-videos#6]
- [x] I have searched the [issues](https://github.com/kzkaneoka/reddit-short-videos/issues) of this repository and believe that this is not a duplicate.

## Description 🎨

- CRUD functionalities for videos such as
  - GET
  - POST
  - PUT
  - DELETE

## Note 📑✏

- Need to work with authentication & authorization after implementing auth functionalities as well.

**Comment by sujeongy** [comment]
@kzkaneoka
Hey, K.
Can we get API url including '/api'?
like `http://localhost:5000/api/videos`

and I though we need set `cors` at backend.
So plz add `cors` library -> https://www.npmjs.com/package/cors

**Comment by Devjacky** [comment]
@kzkaneoka also, can you consider creating a new endpoint to request videos by subreddit?

**Comment by kzkaneoka** [comment]
> @kzkaneoka also, can you consider creating a new endpoint to request videos by subreddit?

That's a good idea! Thanks for suggesting. Do you mean something like `GET HTTP://localhost:5000/api/subreddits/[SUBREDDIT_ID]/videos`?

**Comment by sujeongy** [comment]
@kzkaneoka 
FYI,
just in my case,
LIST GET HTTP://localhost:5000/api/videos
A video GET HTTP://localhost:5000/api/video/:videoId

**Comment by kzkaneoka** [comment]
> @kzkaneoka
> Hey, K.
> Can we get API url including '/api'?
> like `http://localhost:5000/api/videos`

Of course! I set it `/api/v1/videos` currently. I will update it to `/api/videos` for the next PR.

For now, please create `/frontend/routes.json` like below:

```
{
  "/*": "/api/$1"
}
```

and update `scripts` in `/fronend/package.json` as `"json-server": "json-server --watch db.json --routes routes.json --port 5000"`. Then, you should be able to run the API call like `http://localhost:5000/api/videos`.

> and I though we need set `cors` at backend.
> So plz add `cors` library -> https://www.npmjs.com/package/cors

Sure! I'll add it for the next PR.

**Comment by Devjacky** [comment]
#

> > @kzkaneoka also, can you consider creating a new endpoint to request videos by subreddit?
> 
> That's a good idea! Thanks for suggesting. Do you mean something like `GET HTTP://localhost:5000/api/subreddits/[SUBREDDIT_ID]/videos`?

Yes exactly! 😁
